### ISSUE TITLE
NameError: name 'eval_mpfr' is not defined

### ISSUE THREAD

**Issue by jasonrong001** [cbehan/pycftboot#1]
I installed "symengine" and "symengine.py" on ubuntu14.04
and when I run the tutorial.py, it says 
`NameError: name 'eval_mpfr' is not defined`

before that I tried in Python

```
>>> from symengine import var
>>> var("x y z")
(x, y, z)
>>> e = (x+y+z)**2
>>> e.expand()
2*x*y + 2*x*z + 2*y*z + x**2 + y**2 + z**2
```

and it works fine

**Comment by jasonrong001** [comment]
I installed "symengine" with the option 
`-DWITH_MPFR:BOOL=ON`
    and it is working now! Thank you!

**Comment by cbehan** [comment]
I hope the rest continues to work! Maybe there's a way to add a graceful check for this sort of thing.
