### ISSUE TITLE
Shows error with multiple correlators bootstrap in the updated version 

### ISSUE THREAD

**Issue by CSJgroup** [cbehan/pycftboot#12]
Sir,
When we use the multiple correlators bootstrap in the updated version it shows

terminate called after throwing an instance of 'std::invalid_argument'
  what():  mpf_set_str
Traceback (most recent call last):
  File "./Mixed-correlator.py", line 57, in <module>
    result = sdp.iterate()
  File "/pycftboot-master/bootstrap.py", line 1258, in iterate
    terminate_reason = output["terminateReason"]
KeyError: 'terminateReason'

but the old version is working.

**Comment by cbehan** [comment]
Thank-you very much. I found a precision loss issue which might be responsible. Please try the update from today and let me know if it helps.

**Comment by CSJgroup** [comment]
Same to you. Yes, it is working.
