### ISSUE TITLE
About multiple correlators bootstrap

### ISSUE THREAD

**Issue by CSJgroup** [cbehan/pycftboot#14]
Sir,
In 3D, there is some error.

terminate called after throwing an instance of 'std::invalid_argument'
  what():  mpf_set_str
Traceback (most recent call last):
  File "./Mixed-correlator.py", line 63, in <module>
    result = sdp.iterate()
  File "/pycftboot-master/bootstrap.py", line 1260, in iterate
    terminate_reason = output["terminateReason"]
KeyError: 'terminateReason'

But 2D is okay. 
By the way, the updated version is a little bit slow even less value of the parameters.

**Comment by cbehan** [comment]
Does anything appear to be wrong with the XML file when that happens? Does anything change if you uncomment the code block described in the Sep 12 commit? https://github.com/cbehan/pycftboot/commit/97d0ac7aa489478e442e456c8dc1a55eadd8b373

**Comment by CSJgroup** [comment]
Sorry. The error happens because I did not change the unitarity bound. It little bit faster after uncomment this.

**Comment by cbehan** [comment]
Glad it's working now. If you identify a commit that lowers performance other than the incomplete gamma one, please let me know.
