### ISSUE TITLE
'symengine.lib.symengine_wrapper.DenseMatrix' object has no attribute 'submatrix'

### ISSUE THREAD

**Issue by lk11235** [cbehan/pycftboot#2]
Hi I installed the current symengine.py with a compatible commit of symengine (b25a8be8b05a0e6469dd58ef6ef28955912c706d). The pycftboot tutorial.py initiates properly displaying the following:

Welcome to the PyCFTBoot tutorial!
Please read the comments and watch for coloured text.
Which theory would you like to study?
These take increasingly long amounts of time.
1. 3D Ising model (even sector only).
2. 3D O(3) model.
3. 3D Ising model (odd sector as well).
4. 4D N = 1 supersymmetric model.
Choice:

However, upon choosing any of these options, I consistently get this output and error:

Finding basic bound at external dimension 0.518...
Traceback (most recent call last):
  File "tutorial.py", line 44, in <module>
    table1 = bootstrap.ConformalBlockTable(dim, k_max, l_max, m_max, n_max)
  File "/home/icarus/Downloads/pycftboot-master/bootstrap.py", line 698, in **init**
    small_table = ConformalBlockTableSeed(dim, k_max, l_max, min(m_max + 2 \* n_max, 3), 0, delta_12, delta_34, odd_spins)
  File "/home/icarus/Downloads/pycftboot-master/bootstrap.py", line 358, in **init**
    r_sub = r_powers[pol_list[l][i][0]].submatrix(0, derivative_order - j, 0, derivative_order - j)
AttributeError: 'symengine.lib.symengine_wrapper.DenseMatrix' object has no attribute 'submatrix'

I've attempted to try running previous commits of the tutorial/bootstrap to no avail. How can I fix bootstrap.py so that the ConformalBlockTableSeed function doesn't fault at the line requiring a submatrix?

**Comment by isuruf** [comment]
Ah, I didn't think anyone was using the submatrix method.
New way to do this is,
`r_sub = r_powers[pol_list[l][i][0]][0:derivative_order - j+1, 0:derivative_order - j+1]`
instead of,
`r_sub = r_powers[pol_list[l][i][0]].submatrix(0, derivative_order - j, 0, derivative_order - j)`

**Comment by lk11235** [comment]
Thank you -- I was able to get the bootstrap.py functions to compile and run!

**Comment by cbehan** [comment]
Fixed by commit c7fe2a5eaa0aa656e3e4401fe9b43e0f7012a22f.

**Comment by cbehan** [comment]
Fixed by commit c7fe2a5eaa0aa656e3e4401fe9b43e0f7012a22f. Thanks!

**Comment by lk11235** [comment]
I seem to be getting incorrect values from the bootstrap.py calculations though (that are in your paper "PyCFTBoot: A flexible interface for the conformal bootstrap"). When running your example for identical scalars (displayed below) I get a value of 0.7 instead of the supposedly correct of 1.434375:

>>> from bootstrap import *
>>> table1 = ConformalBlockTable(3, 15, 15, 1, 3)
>>> table2 = ConvolvedBlockTable(table1)
>>> sdp = SDP(0.52, table2)
>>> result = sdp.bisect(0.7, 1.7, 0.01, 0)
>>> result
0.7

How can I remedy this?
