### ISSUE TITLE
Question: CalledProcessError running tutorial.py

### ISSUE THREAD

**Issue by oikawa-t** [cbehan/pycftboot#23]
I use `Debian 10.5` via Docker for Windows and install `Python 2.7.16`, `SDPB 2.4.0`  and other requirements.   
Then I  tried to run `tutorial.py` and selected tutorial example 1 (3D Ising). At first, it seems to run well, but I got the following output and error after several calculating steps;

```
Loading binary checkpoint from : "mySDP.ck"
Process 0 caught error message:
Incompatible binary checkpoint file.  For block with global size (1,1), expected local dimensions (1,1), but found (18,18)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "tutorial.py", line 66, in <module>
    allowed = sdp.iterate()
  File "/home/oikawa/conformal/pycftboot/bootstrap.py", line 1257, in iterate
    subprocess.check_call([mpirun_path, "-n", ppn, sdpb_path, "-s", name, "--precision=" + str(prec), "--findPrimalFeasible", "--findDualFeasible"] + self.options)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/mpirun', '-n', '1', '/home/oikawa/conformal/SDPB/build/sdpb', '-s', 'mySDP', '--precision=660', '--findPrimalFeasible', '--findDualFeasible', '--procsPerNode=1']' returned non-zero exit status 1
```

When I select other tutorial examples of theory, I also get the same error and process stops.  
I can't understand what happens here. Where and how do I fix this error?

**Comment by cbehan** [comment]
Good point. Since writing the tutorial, I enabled checkpoints which results in much faster bisections for users of SDPB2. However, this means it is a problem for the tutorial to keep using the default name whenever it runs SDPB. Sometimes the file called "mySDP.xml" has nothing to do with a previous file that was also called "mySDP.xml" and it no longer makes sense to load the checkpoint.

Please try the latest version which uses explicit non-conflicting names.

**Comment by oikawa-t** [comment]
Thanks for updating and sorry for the late response.
After replacing `tutorial.py` and  `bootstrap.py` to the latest ones, I retried to run example 1 in `tutorial.py`. But I caught an error message:
```
Traceback (most recent call last):
  File "tutorial.py", line 58, in <module>
    result = sdp.bisect(lower, upper, tol, channel, name = "tutorial_1a")
TypeError: bisect() got an unexpected keyword argument 'name'
```
I guessed 'name' keyword should be added to the definition of bisect(), so I modified two points in `bootstrap.py` :

- Line 1265 ; <pre>def bisect(self, lower, upper, threshold, spin_irrep, isolated = False, reverse = False, bias = None, <b>name = "mySDP"</b>)</pre>
- Line 1328 ; <pre>result = self.iterate(<b>name = name</b>)</pre>
Then all examples run well, but perhaps these modifications lead to bad effect without noticing.

**Comment by cbehan** [comment]
Somehow I thought bisect() was already like that. Thanks for the suggestion which I have now applied :).
