### ISSUE TITLE
unable to import symengine and bootstrap

### ISSUE THREAD

**Issue by imaneekjana** [cbehan/pycftboot#24]
using MacOS

unable to import symnegine
>>> import symengine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aneekphys/opt/anaconda3/lib/python3.9/site-packages/symengine/__init__.py", line 12, in <module>
    import symengine.lib.symengine_wrapper as wrapper
ImportError: dlopen(/Users/aneekphys/opt/anaconda3/lib/python3.9/site-packages/symengine/lib/symengine_wrapper.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN9SymEngine10ComplementC1ERKNS_3RCPIKNS_3SetEEES6_)

unable to import bootstrap
>>> import bootstrap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bootstrap'
 

though I have sdpb, symengine installed, and PyCFTBoot repo cloned in my machine.

However, all other steps in the Installation guide for MacOS are successful.

**Comment by cbehan** [comment]
You need to recompile symengine and/or symengine.py. Most likely you have performed a major python update since they were installed. The second problem is simply that you aren't running python from the pycftboot directory. But neither of these are bugs.

**Comment by imaneekjana** [comment]
I am able to import bootstrap now but the problem continues with symengine (with the same specific error message). 
I don't know how to resolve.

**Comment by imaneekjana** [comment]
>>> import symengine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aneekphys/symengine/build/symengine.py/symengine/__init__.py", line 12, in <module>
    import symengine.lib.symengine_wrapper as wrapper
ImportError: dlopen(/Users/aneekphys/symengine/build/symengine.py/symengine/lib/symengine_wrapper.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (__ZN9SymEngine10ComplementC1ERKNS_3RCPIKNS_3SetEEES6_)

**Comment by cbehan** [comment]
Whatever you did to install symengine should just be redone. Uninstall it and then reinstall it. If the error still happens after that you'll have to ask the symengine people.

**Comment by imaneekjana** [comment]
Thanks, the issue is resolved
