### ISSUE TITLE
Incorrect calculations?

### ISSUE THREAD

**Issue by lk11235** [cbehan/pycftboot#3]
I seem to be getting incorrect values from the bootstrap.py calculations though (that are in your paper "PyCFTBoot: A flexible interface for the conformal bootstrap"). When running your example for identical scalars (displayed below) I get a value of 0.7 instead of the supposedly correct of 1.434375:

> > > from bootstrap import *
> > > table1 = ConformalBlockTable(3, 15, 15, 1, 3)
> > > table2 = ConvolvedBlockTable(table1)
> > > sdp = SDP(0.52, table2)
> > > result = sdp.bisect(0.7, 1.7, 0.01, 0)
> > > result
> > > 0.7

How can I remedy this?

**Comment by cbehan** [comment]
I cannot reproduce this. Are you using the latest commit?

**Comment by lk11235** [comment]
With the latest commit, I get a different error:

Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from bootstrap import *
> > > table1 = ConformalBlockTable(3, 15, 15, 1, 3)
> > > table2 = ConvolvedBlockTable(table1)
> > > sdp = SDP(0.52, table2)
> > > result = sdp.bisect(0.7, 1.7, 0.01, 0)
> > > Trying 1.2

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bootstrap.py", line 1105, in bisect
    result = self.iterate()
  File "bootstrap.py", line 1074, in iterate
    out_file = open(name + ".out", 'r')
IOError: [Errno 2] No such file or directory: 'mySDP.out'

**Comment by cbehan** [comment]
Then the optimization didn't finish. Is there any sign that SDPB started to run and are you able to run it yourself? Also, does the user python is running as have permission to create the mySDP.xml file?

**Comment by lk11235** [comment]
I was able to fix it! You were right it was the SDPB. I also modified the iterate function so that it could create a mySDP.out if the file didn't already exist. Thank you!

**Comment by rmkaadhi** [comment]
Can you please help me, How to resolve this issue.

Trying 3.5
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    result = sdp.bisect(0.00, 7.00, 0.01, 0)
  File "/storage/home/jagannath/more-correlators/pycftboot-master/bootstrap.py", line 1283, in bisect
    result = self.iterate()
  File "/storage/home/jagannath/more-correlators/pycftboot-master/bootstrap.py", line 1215, in iterate
    output = self.read_output(name = name)
  File "/storage/home/jagannath/more-correlators/pycftboot-master/bootstrap.py", line 1188, in read_output
    out_file = open(name + ".out", 'r')
IOError: [Errno 2] No such file or directory: 'mySDP.out'

**Comment by rmkaadhi** [comment]
> I was able to fix it! You were right it was the SDPB. I also modified the iterate function so that it could create a mySDP.out if the file didn't already exist. Thank you!

**Comment by rmkaadhi** [comment]
> I was able to fix it! You were right it was the SDPB. I also modified the iterate function so that it could create a mySDP.out if the file didn't already exist. Thank you!

How to resolve this issue?

**Comment by cbehan** [comment]
Again, it looks like SDPB was not called. What happens when you run "sdpb -s mySDP.xml" manually?

**Comment by CSJgroup** [comment]
When we run this command: We have seen
[jagannath@kalinga pycftboot-master]$ sdpb -s mySDP.xml 
SDPB started at 2019-Feb-08 15:04:08
SDP file        : "mySDP.xml"
out file        : "mySDP.out"
checkpoint in   : "mySDP.ck"
checkpoint out  : "mySDP.ck"

Parameters:
maxIterations                = 500
maxRuntime                   = 86400
checkpointInterval           = 3600
noFinalCheckpoint            = false
findPrimalFeasible           = false
findDualFeasible             = false
detectPrimalFeasibleJump     = false
detectDualFeasibleJump       = false
precision(actual)            = 400(448)
maxThreads(using)            = 4(4)
dualityGapThreshold          = 1e-30
primalErrorThreshold         = 1e-30
dualErrorThreshold           = 1e-30
initialMatrixScalePrimal     = 100000000000000000000
initialMatrixScaleDual       = 100000000000000000000
feasibleCenteringParameter   = 0.1
infeasibleCenteringParameter = 0.3
stepLengthReduction          = 0.7
choleskyStabilizeThreshold   = 1e-40
maxComplementarity           = 1e+100


     time      mu        P-obj       D-obj      gap         P-err       D-err      P-step   D-step   beta  dim/stabilized
-------------------------------------------------------------------------------------------------------------------------
  1  00:00:00  1.0e+40  +0.00e+00   +0.00e+00   0.00e+00   +1.00e+20   +5.45e+21   0.365    0.498    0.3   14/14
  2  00:00:00  7.3e+39  +3.21e+04   +0.00e+00   1.00e+00   +6.35e+19   +2.74e+21   0.376    0.524    0.3   14/14
  3  00:00:00  5.3e+39  +6.12e+04   +0.00e+00   1.00e+00   +3.96e+19   +1.30e+21   0.545    0.396    0.3   14/14

................................................last few lines...............................................
186  00:00:33  1.2e-32  +2.69e-30   +0.00e+00   2.69e-30   +4.42e-118  +7.52e-78   0.778    0.778    0.1   14/14
-----found primal-dual optimal solution----------------------------------------------------------------------------------

primalObjective = 8.0715742405024980239366218774e-31
dualObjective   = 0
dualityGap      = 8.0715742405024980239366218774e-31
primalError     = 2.43425518754541452606848077306e-118
dualError       = 1.67140405078988673995108996029e-78

Saving checkpoint to    : "mySDP.ck"
Saving solution to      : "mySDP.out"

Last checkpoint	: 0.000448s wall, 0.000000s user + 0.000000s system = 0.000000s CPU (n/a%)
Solver runtime	: 33.066631s wall, 129.050000s user + 0.060000s system = 129.110000s CPU (390.5%)

**Comment by rmkaadhi** [comment]
Thanks, it is working. After copying the executable to /usr/bin

**Comment by CSJgroup** [comment]
Thanks. It is running. After changing the sdpb_path.
