### ISSUE TITLE
Question: running the Tutorial failed (fixed)

### ISSUE THREAD

**Issue by yinchenhe** [cbehan/pycftboot#8]
I was trying to run the tutorial, but it failed. Following is the message I got. 

Welcome to the PyCFTBoot tutorial!
Please read the comments and watch for coloured text.
Which theory would you like to study?
These take increasingly long amounts of time.
1. 3D Ising model (even sector only).
2. 3D O(3) model.
3. 3D Ising model (odd sector as well).
4. 4D N = 1 supersymmetric model.
Choice: 1
Finding basic bound at external dimension 0.518...
Trying 1.2
SDPB started at 2017-Sep-06 22:47:30
SDP file        : "mySDP.xml"
out file        : "mySDP.out"
checkpoint in   : "mySDP.ck"
checkpoint out  : "mySDP.ck"

Parameters:
maxIterations                = 500
maxRuntime                   = 86400
checkpointInterval           = 3600
noFinalCheckpoint            = true
findPrimalFeasible           = true
findDualFeasible             = true
detectPrimalFeasibleJump     = false
detectDualFeasibleJump       = false
precision(actual)            = 660(704)
maxThreads(using)            = 4(4)
dualityGapThreshold          = 1e-30
primalErrorThreshold         = 1e-30
dualErrorThreshold           = 1e-30
initialMatrixScalePrimal     = 100000000000000000000
initialMatrixScaleDual       = 100000000000000000000
feasibleCenteringParameter   = 0.1
infeasibleCenteringParameter = 0.3
stepLengthReduction          = 0.7
choleskyStabilizeThreshold   = 1e-40
maxComplementarity           = 1e+100

     time      mu        P-obj       D-obj      gap         P-err       D-err      P-step   D-step   beta  dim/stabilized
-------------------------------------------------------------------------------------------------------------------------
Assertion failed: (info == 0), function LUDecomposition, file src/Matrix.cpp, line 196.
Traceback (most recent call last):
  File "tutorial.py", line 58, in <module>
    result = sdp.bisect(lower, upper, tol, channel)
  File "bootstrap.py", line 1256, in bisect
    result = self.iterate()
  File "bootstrap.py", line 1190, in iterate
    terminate_reason = output["terminateReason"]
KeyError: 'terminateReason'

**Comment by yinchenhe** [comment]
It is fixed now. It seems that I didn't install symengine.py properly.

**Comment by cbehan** [comment]
Glad to hear it.
